swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /medlemmer:
    x-swagger-router-controller: medlemmer
    get:
      description: Hent medlemsinfo
      operationId: listall
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Nytt medlem
      operationId: ny
      consumes:
        - application/json
      parameters:
        - name: data
          in: body
          description: medlemsdata
          required: true
          schema:
            $ref: "#/definitions/Medlem"
      responses:
        "200":
          description: Success
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /medlemmer/{id}:
    x-swagger-router-controller: medlemmer
    get:
      description: Hent medlemsinfo
      operationId: list
      parameters:
        - name: id
          in: path
          description: person-id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Lagre medlem
      operationId: registrer
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: person-id
          required: true
          type: string
        - name: data
          in: body
          description: medlemsdata
          required: true
          schema:
            $ref: "#/definitions/Medlem"
      responses:
        "200":
          description: Success
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Medlem:
    required:
      - navn
      - hovedinstrument
    properties:
      navn:
        type: string
        pattern: '^[a-zA-Z0-9_-]+$'
      hovedinstrument:
        type: string
        enum: [fløyte, klarinett, fagott, saxofon, horn, trompet, trombone, euphonium, baryton, tuba, slagverk]
      biinstrumenter:
        type: array
        items:
          type: string
          enum: [fløyte, klarinett, fagott, saxofon, horn, trompet, trombone, euphonium, baryton, tuba, slagverk]